#pragma once
#include <unordered_map>
#include <string>
#include <algorithm>
#include <cctype>

static std::unordered_map<std::string, std::string> g_ItemNames = {
    {"FireflyLantern", "Candelabra"},
    {"Item_Camper_AlexsToolbox", "Alex's Toolbox"},
    {"Item_Camper_AnniversaryToolbox", "Anniversary Toolbox"},
    {"Item_Camper_BeigeMap", "Scribbled Map"},
    {"Item_Camper_BrokenKey", "Broken Key"},
    {"Item_Camper_CommodiousToolbox", "Commodious Toolbox"},
    {"Item_Camper_ContaminationSerum", "Vaccine"},
    {"Item_Camper_DullKey", "Dull Key"},
    {"Item_Camper_EngineerToolbox", "Engineer's Toolbox"},
    {"Item_Camper_FadedMap", "Cryptic Map"},
    {"Item_Camper_Firecracker_Anniversary2019", "Third Year Party Starter"},
    {"Item_Camper_Firecracker_Chinese", "Chinese Firecracker"},
    {"Item_Camper_Firecracker_Flashbang", "Flash Grenade"},
    {"Item_Camper_Firecracker_WinterEvent", "Winter Party Starter"},
    {"Item_Camper_Flashlight", "Flashlight"},
    {"Item_Camper_Flashlight_Anniversary2020", "Anniversary Flashlight"},
    {"Item_Camper_Flashlight_Anniversary2022", "Masquerade Flashlight"},
    {"Item_Camper_Flashlight_Random", "Flashlight"},
    {"Item_Camper_Flashlight02", "Sport Flashlight"},
    {"Item_Camper_Flashlight03", "Utility Flashlight"},
    {"Item_Camper_Flashlight04", "Will O' Wisp"},
    {"Item_Camper_JerryCan_Spring2025", "Blood Can"},
    {"Item_Camper_K29InfectionRemover", "First Aid Spray"},
    {"Item_Camper_K32Emp", "EMP"},
    {"Item_Camper_K33Turret", "Remote Flame Turret"},
    {"Item_Camper_K36MagicItem_Boots", "Boots of {0}"},
    {"Item_Camper_K36MagicItem_Bracers", "@#K36_MagicItem_Bracers_NAME"},
    {"Item_Camper_K36MagicItem_VecnaEye", "Eye Of Vecna"},
    {"Item_Camper_K36MagicItem_VecnaHand", "Hand Of Vecna"},
    {"Item_Camper_Key", "Skeleton Key"},
    {"Item_Camper_Key_Random", "Skeleton Key"},
    {"Item_Camper_LunarToolbox", "Festive Toolbox"},
    {"Item_Camper_Map_Random", "Cryptic Map"},
    {"Item_Camper_Map_Spring2024", "Bloodsense Map"},
    {"Item_Camper_MechanicsToolbox", "Mechanic's Toolbox"},
    {"Item_Camper_MedKit", "Camping Aid Kit"},
    {"Item_Camper_Medkit_Anniversary2020", "Anniversary Med-kit"},
    {"Item_Camper_Medkit_Anniversary2022", "Masquerade Med-Kit"},
    {"Item_Camper_MedKit_Random", "Camping Aid Kit"},
    {"Item_Camper_MedKit02", "First Aid Kit"},
    {"Item_Camper_MedKit03", "Emergency Med-kit"},
    {"Item_Camper_MedKit04", "Ranger Med-kit"},
    {"Item_Camper_Medkit05", "All Hallows' Eve Lunchbox"},
    {"Item_Camper_OnryoTape", "Item_Camper_OnryoTape"},
    {"Item_Camper_RainbowMap", "Annotated Map"},
    {"Item_Camper_Toolbox", "Toolbox"},
    {"Item_Camper_Toolbox_Anniversary2022", "Masquerade Toolbox"},
    {"Item_Camper_Toolbox_Random", "Toolbox"},
    {"Item_Camper_VoidBomb_Halloween2024", "Void Crystal"},
    {"Item_Camper_WornoutToolbox", "Worn-out Tools"},
    {"Item_FragileObject", "Pocket Mirror"},
    {"Item_LamentConfiguration", "Lament Configuration"},
    {"Item_Slasher_Beartrap", "Bear Trap"},
    {"Item_Slasher_Blinker", "Spencer's Last Breath"},
    {"Item_Slasher_Chainsaw", "Chainsaw"},
    {"Item_Slasher_CloakBell", "Wailing Bell"},
    {"Item_Slasher_DreamInducer", "Dream Demon"},
    {"Item_Slasher_Frenzy", "Feral Frenzy"},
    {"Item_Slasher_GasBomb", "The Afterpiece Tonic"},
    {"Item_Slasher_GhostPower", "Night Shroud"},
    {"Item_Slasher_HarpoonRifle", "The Redeemer"},
    {"Item_Slasher_Hatchet", "Hunting Hatchets"},
    {"Item_Slasher_K21Power", "Blighted Corruption"},
    {"Item_Slasher_K22Power", "Blood Bond"},
    {"Item_Slasher_K24Power", "T-VIRUS"},
    {"Item_Slasher_K25Power", "Summons of Pain"},
    {"Item_Slasher_K26Power", "Birds of Torment"},
    {"Item_Slasher_K27Power", "Deluge of Fear"},
    {"Item_Slasher_K28Power", "Reign of Darkness"},
    {"Item_Slasher_K29Power", "Virulent Bound"},
    {"Item_Slasher_K30Power", "Guardia Compagnia"},
    {"Item_Slasher_K31Power", "Eyes In The Sky"},
    {"Item_Slasher_K32Power", "Quantum Instantiation"},
    {"Item_Slasher_K33Power", "Hidden Pursuit"},
    {"Item_Slasher_K34Power", "Playtime's Over"},
    {"Item_Slasher_K35Power", "UVX"},
    {"Item_Slasher_K36Power", "VILE DARKNESS"},
    {"Item_Slasher_K37Power", "Vampiric Shift"},
    {"Item_Slasher_K38Power", "Scent of Blood"},
    {"Item_Slasher_K39Power", "One-Eyed Terror"},
    {"Item_Slasher_K40Power", "Fazbear's Fright"},
    {"Item_Slasher_K41Power", "Unbodied Flesh"},
    {"Item_Slasher_K42Power", "Test Subject #001"},
    {"Item_Slasher_Kanobo", "Yamaoka's Wrath"},
    {"Item_Slasher_Killer07Item", "Carter's Spark"},
    {"Item_Slasher_LFChainsaw", "Bubba's Chainsaw"},
    {"Item_Slasher_PhantomTrap", "Blackened Catalyst"},
    {"Item_Slasher_PhaseWalker", "Yamaoka’s Haunting"},
    {"Item_Slasher_PlaguePower", "Vile Purge"},
    {"Item_Slasher_QatarKillerPower", "Of the Abyss"},
    {"Item_Slasher_ReverseBearTrap", "Jigsaw's Baptism"},
    {"Item_Slasher_Stalker", "Evil Within"},
    {"Item_Slasher_ThrowingKnives", "Showstopper"},
    {"Item_Slasher_TormentMode", "Rites of Judgment"},
    {"Item_Survivor_CalamariContaminationAntidote", "Antidote"},
    {"Item_Survivor_K41Mushroom", "Glowing Fungus"},
    {"Item_Survivor_MakeshiftFogVial", "Apprentice's Fog Vial"},
    {"Item_Survivor_PrototypeFogVial", "Artisan's Fog Vial"},
    {"Item_Survivor_VigosFogVial", "Vigo's Fog Vial"},
};

static std::unordered_map<std::string, std::string> g_AddonNames = {
    {"Addon_Beartrap_001", "Honing Stone"},
    {"Addon_Beartrap_002", "Serrated Jaws"},
    {"Addon_Beartrap_003", "Trapper Bag"},
    {"Addon_Beartrap_004", "Wax Brick"},
    {"Addon_Beartrap_005", "Lengthened Jaws"},
    {"Addon_Beartrap_006", "Tar Bottle"},
    {"Addon_Beartrap_007", "Makeshift Wrap"},
    {"Addon_Beartrap_008", "4-Coil Spring Kit"},
    {"Addon_Beartrap_009", "Trapper Sack"},
    {"Addon_Beartrap_010", "Trapper Gloves"},
    {"Addon_Beartrap_011", "Secondary Coil"},
    {"Addon_Beartrap_012", "Fastening Tools"},
    {"Addon_Beartrap_PaddedJaws", "Padded Jaws"},
    {"Addon_Beartrap_TrapperSack", "Bear Oil"},
    {"Addon_Bell_001", "Bone Clapper"},
    {"Addon_Bell_002", "\"The Ghost\" - Soot"},
    {"Addon_Bell_003", "\"The Hound\" - Soot"},
    {"Addon_Bell_004", "\"Blind Warrior\" - Mud"},
    {"Addon_Bell_005", "\"Swift Hunt\" - Mud"},
    {"Addon_Bell_006", "\"Swift Hunt\" - Blood"},
    {"Addon_Bell_007", "\"The Beast\" - Soot"},
    {"Addon_Bell_008", "\"All Seeing\" - Blood"},
    {"Addon_Bell_009", "\"Windstorm\"- Mud"},
    {"Addon_Bell_010", "\"Windstorm\" - White"},
    {"Addon_Bell_011", "\"Blink\" - Mud"},
    {"Addon_Bell_012", "\"Blink\" - White"},
    {"ADDON_Bell_AllseeingSpirit", "\"All Seeing\" - Spirit"},
    {"ADDON_Bell_AllseeingWhite", "\"The Serpent\" - Soot"},
    {"ADDON_Bell_BlindBlood", "\"Shadow Dance\" - White"},
    {"ADDON_Bell_BlindSpirit", "\"Shadow Dance\" - Blood"},
    {"ADDON_Bell_BlindWhite", "\"Blind Warrior\" - White"},
    {"ADDON_Bell_CoxcombedClapper", "Coxcombed Clapper"},
    {"ADDON_Bell_SwiftMud", "\"Swift Hunt\" - White"},
    {"ADDON_Bell_WindstormBlood", "\"Windstorm\" - Blood"},
    {"Addon_Blinker_001", "Plaid Flannel"},
    {"Addon_Blinker_002", "White Nit Comb"},
    {"Addon_Blinker_003", "Pocket Watch"},
    {"Addon_Blinker_004", "Anxious Gasp"},
    {"Addon_Blinker_005", "Torn Bookmark"},
    {"Addon_Blinker_006", "Dark Cincture"},
    {"Addon_Blinker_007", "Fragile Wheeze"},
    {"Addon_Blinker_008", "Campbell's Last Breath"},
    {"Addon_Blinker_009", "Metal Spoon"},
    {"Addon_Blinker_010", "Bad Man Keepsake"},
    {"Addon_Blinker_011", "Wooden Horse"},
    {"Addon_Blinker_012", "Catatonic Boy's Treasure"},
    {"Addon_Chainsaw_001", "Dad's Boots"},
    {"Addon_Chainsaw_002", "Counterweight"},
    {"Addon_Chainsaw_003", "Greased Throttle"},
    {"Addon_Chainsaw_004", "Thermal Casing"},
    {"Addon_Chainsaw_005", "Steel Toe Boots"},
    {"Addon_Chainsaw_006", "The Thompsons' Mix"},
    {"Addon_Chainsaw_007", "Begrimed Chains"},
    {"Addon_Chainsaw_008", "Ragged Engine"},
    {"Addon_Chainsaw_009", "Lo Pro Chains"},
    {"Addon_Chainsaw_010", "Discarded Air Filter"},
    {"Addon_Chainsaw_011", "Cracked Primer Bulb"},
    {"Addon_Chainsaw_012", "Off-Brand Motor Oil"},
    {"ADDON_Chainsaw_CarburatorGuide", "Tuned Carburetor"},
    {"ADDON_Chainsaw_DeathEngravings", "Clogged Intake"},
    {"ADDON_Chainsaw_DoomEngravings", "Iridescent Engravings"},
    {"ADDON_Chainsaw_HomemadeMuffler", "Apex Muffler"},
    {"ADDON_Chainsaw_LightChassis", "Low Kickback Chains"},
    {"ADDON_Chainsaw_ThompsonMix", "High-Speed Idler Screw"},
    {"ADDON_Chainsaw_ThompsonMoonshine", "Spiked Boots"},
    {"Addon_Demogorgon_BarbsGlasses", "Barb's Glasses"},
    {"Addon_Demogorgon_BlackHeart", "Black Heart"},
    {"Addon_Demogorgon_BrassCaseLighter", "Brass Case Lighter"},
    {"Addon_Demogorgon_DeerLung", "Deer Lung"},
    {"Addon_Demogorgon_ElevensSoda", "Eleven's Soda"},
    {"Addon_Demogorgon_LerproseLichen", "Leprose Lichen"},
    {"Addon_Demogorgon_LifeguardWhistle", "Lifeguard Whistle"},
    {"Addon_Demogorgon_MewsGuts", "Mew's Guts"},
    {"Addon_Demogorgon_RatLiver", "Rat Liver"},
    {"Addon_Demogorgon_RatTail", "Rat Tail"},
    {"Addon_Demogorgon_RedMoss", "Red Moss"},
    {"Addon_Demogorgon_RottenGreenTripe", "Rotten Green Tripe"},
    {"Addon_Demogorgon_RottenPumpkin", "Rotten Pumpkin"},
    {"Addon_Demogorgon_StickyLining", "Sticky Lining"},
    {"Addon_Demogorgon_ThornyVines", "Thorny Vines"},
    {"Addon_Demogorgon_UnknownEgg", "Unknown Egg"},
    {"Addon_Demogorgon_UpsideDownResin", "Upside Down Resin"},
    {"Addon_Demogorgon_VermillionWebcap", "Vermillion Webcap"},
    {"Addon_Demogorgon_VioletWaxCap", "Violet Waxcap"},
    {"Addon_Demogorgon_ViscousWebbing", "Viscous Webbing"},
    {"Addon_DreamInducer_BlackBox", "Black Box"},
    {"Addon_DreamInducer_BlueDress", "Blue Dress"},
    {"Addon_DreamInducer_CatBlock", "Cat Block"},
    {"Addon_DreamInducer_ClassPhoto", "Class Photo"},
    {"Addon_DreamInducer_GardenRake", "Garden Rake"},
    {"Addon_DreamInducer_GreenDress", "Green Dress"},
    {"Addon_DreamInducer_JumpRope", "Jump Rope"},
    {"Addon_DreamInducer_KidsDrawing", "Kid's Drawing"},
    {"Addon_DreamInducer_NancysMasterpiece", "Nancy's Masterpiece"},
    {"Addon_DreamInducer_NancysSketch", "Nancy's Sketch"},
    {"Addon_DreamInducer_PaintThinner", "Paint Thinner"},
    {"Addon_DreamInducer_PillBottle", "Pill Bottle"},
    {"Addon_DreamInducer_PrototypeClaws", "Prototype Claws"},
    {"Addon_DreamInducer_RedPaintBrush", "Red Paint Brush"},
    {"Addon_DreamInducer_Rope", "Outdoor Rope"},
    {"Addon_DreamInducer_SheepBlock", "Sheep Block"},
    {"Addon_DreamInducer_SwingChains", "Swing Chains"},
    {"Addon_DreamInducer_UnicornBlock", "Unicorn Block"},
    {"Addon_DreamInducer_WoolShirt", "Wool Shirt"},
    {"Addon_DreamInducer_ZBlock", "\"Z\" Block"},
    {"Addon_Flashlight_001", "Battery"},
    {"Addon_Flashlight_002", "Heavy Duty Battery"},
    {"Addon_Flashlight_003", "Focus Lens"},
    {"Addon_Flashlight_004", "Wide Lens"},
    {"Addon_Flashlight_005", "Power Bulb"},
    {"Addon_Flashlight_006", "TIR Optic"},
    {"Addon_Flashlight_007", "Low Amp Filament"},
    {"Addon_Flashlight_008", "Leather Grip"},
    {"Addon_Flashlight_BrokenBulb", "Broken Bulb"},
    {"ADDON_flashlight_highendsapphire", "High-end Sapphire lens"},
    {"ADDON_flashlight_intensehalogen", "Intense Halogen"},
    {"ADDON_flashlight_lonflifebattery", "Long Life Battery"},
    {"ADDON_flashlight_oddbulb", "Odd Bulb"},
    {"ADDON_flashlight_rubbergrip", "Rubber Grip"},
    {"Addon_FogVial_Accelerant", "Volcanic Stone"},
    {"Addon_FogVial_Amplifier", "Mushroom Formula"},
    {"Addon_FogVial_DenseFogExtract", "Potent Extract"},
    {"Addon_FogVial_LargeVial", "Reactive Compound"},
    {"Addon_FogVial_SlowRelease", "Oily Sap"},
    {"ADDON_Frenzy_ColdDirt", "BFFs"},
    {"ADDON_Frenzy_DefacedSmileyPin", "Defaced Smiley Pin"},
    {"ADDON_Frenzy_EtchedRuler", "Etched Ruler"},
    {"ADDON_Frenzy_FilthyBlade", "Filthy Blade"},
    {"ADDON_Frenzy_FranksMixTape", "Frank's Mix Tape"},
    {"ADDON_Frenzy_FriendshipBracelet", "Friendship Bracelet"},
    {"ADDON_Frenzy_FumingMixTape", "Fuming Mix Tape"},
    {"ADDON_Frenzy_IridescentButton", "Iridescent Button"},
    {"ADDON_Frenzy_JoeysMixTape", "Joey's Mix Tape"},
    {"ADDON_Frenzy_JuliesMixTape", "Julie's Mix Tape"},
    {"ADDON_Frenzy_MischiefList", "Mischief List"},
    {"ADDON_Frenzy_MuralSketch", "Mural Sketch"},
    {"ADDON_Frenzy_NastyBlade", "Stylish Sunglasses"},
    {"ADDON_Frenzy_NeverSleepPills", "Never-Sleep Pills"},
    {"ADDON_Frenzy_ScratchedRuler", "Scratched Ruler"},
    {"ADDON_Frenzy_SmileyFacePin", "Smiley Face Pin"},
    {"ADDON_Frenzy_StabWoundsStudy", "Stab Wounds Study"},
    {"ADDON_Frenzy_StolenSketchBook", "Stolen Sketch Book"},
    {"ADDON_Frenzy_SusiesMixTape", "Susie's Mix Tape"},
    {"ADDON_Frenzy_TheLegionPin", "The Legion Pin"},
    {"Addon_GasBomb_01", "Robin Feather"},
    {"Addon_GasBomb_02", "Party Bottle"},
    {"Addon_GasBomb_03", "Smelly Inner Soles"},
    {"Addon_GasBomb_04", "Fingerless Parade Gloves"},
    {"Addon_GasBomb_05", "Thick Cork Stopper"},
    {"Addon_GasBomb_06", "Solvent Jug"},
    {"Addon_GasBomb_07", "Kerosene Can"},
    {"Addon_GasBomb_08", "Sticky Soda Bottle"},
    {"Addon_GasBomb_09", "Starling Feather"},
    {"Addon_GasBomb_10", "VHS Porn"},
    {"Addon_GasBomb_11", "Spirit of Hartshorn"},
    {"Addon_GasBomb_12", "Sulfuric Acid Vial"},
    {"Addon_GasBomb_13", "Flask of Bleach"},
    {"Addon_GasBomb_14", "Bottle of Chloroform"},
    {"Addon_GasBomb_15", "Garish Makeup Kit"},
    {"Addon_GasBomb_16", "Cheap Gin Bottle"},
    {"Addon_GasBomb_17", "Ether 15 vol%"},
    {"Addon_GasBomb_18", "Cigar Box"},
    {"Addon_GasBomb_19", "Tattoo's Middle Finger"},
    {"Addon_GasBomb_19a", "@#Addon_GasBomb_19a_NAME"},
    {"Addon_GasBomb_20", "Redhead's Pinky Finger"},
    {"Addon_GasBomb_20a", "@#Addon_GasBomb_20a_NAME"},
    {"Addon_GasBomb_20b", "@#Addon_GasBomb_20b_NAME"},
    {"Addon_Ghost_CheapCologne", "Cheap Cologne"},
    {"Addon_Ghost_ChewedPen", "Chewed Pen"},
    {"Addon_Ghost_DriversLicense", "Driver's License"},
    {"Addon_Ghost_DropLegKnifeSheath", "Drop-Leg Knife Sheath"},
    {"Addon_Ghost_HeadlinesCutouts", "Headline Cutouts"},
    {"Addon_Ghost_KnifeBeltClip", "Knife Belt Clip"},
    {"Addon_Ghost_LastingPerfume", "Lasting Perfume"},
    {"Addon_Ghost_LeatherKnifeSheath", "Leather Knife Sheath"},
    {"Addon_Ghost_MarkedMap", "Marked Map"},
    {"Addon_Ghost_NightVisionMonocular", "Night Vision Monocular"},
    {"Addon_Ghost_OlsensAddressBook", "Olsen's Address Book"},
    {"Addon_Ghost_OlsensJournal", "Olsen’s Journal"},
    {"Addon_Ghost_OlsensWallet", "Olsen’s Wallet"},
    {"Addon_Ghost_OutdoorSecurityCamera", "Outdoor Security Camera"},
    {"Addon_Ghost_Philly", "“Philly”"},
    {"Addon_Ghost_ReusableCinchStraps", "Cinch Straps"},
    {"Addon_Ghost_TelephotoLens", "Telephoto Lens"},
    {"Addon_Ghost_TheGhostFaceCaughtOnTape", "“Ghost Face Caught on Tape”"},
    {"Addon_Ghost_VictimsDetailedRoutine", "Victim’s Detailed Routine"},
    {"Addon_Ghost_WalleyesMatchbook", "Walleye's Matchbook"},
    {"Addon_Harpoon_BarbedWire", "Barbed Wire"},
    {"Addon_Harpoon_BayshoresCigar", "Bayshore’s Cigar"},
    {"Addon_Harpoon_BayshoresGoldTooth", "Bayshore’s Gold Tooth"},
    {"Addon_Harpoon_ChewingTobacco", "Chewing Tobacco"},
    {"Addon_Harpoon_ClearCreekWhiskey", "Gold Creek Whiskey"},
    {"Addon_Harpoon_HellshireIron", "Hellshire Iron"},
    {"Addon_Harpoon_HoneyLocustThorns", "Honey Locust Thorns"},
    {"Addon_Harpoon_IridescentCoin", "Iridescent Coin"},
    {"Addon_Harpoon_JawSmasher", "Jaw Smasher"},
    {"Addon_Harpoon_MarshalsBadge", "Marshal's Badge"},
    {"Addon_Harpoon_ModifiedAmmoBelt", "Modified Ammo Belt"},
    {"Addon_Harpoon_PoisonOakLeaves", "Poison Oak Leaves"},
    {"Addon_Harpoon_PrisonChain", "Prison Chain"},
    {"Addon_Harpoon_RicketyChain", "Rickety Chain"},
    {"Addon_Harpoon_RustedSpike", "Rusted Spike"},
    {"Addon_Harpoon_SnakeOil", "Snake Oil"},
    {"Addon_Harpoon_SpitPolishRag", "Spit Polish Rag"},
    {"Addon_Harpoon_TinOilCan", "Tin Oil Can"},
    {"Addon_Harpoon_WantedPoster", "Wanted Poster"},
    {"Addon_Harpoon_WardensKeys", "Warden’s Keys"},
    {"Addon_Hatchet_AmanitaToxin", "Amanita Toxin"},
    {"Addon_Hatchet_BandagedHaft", "Bandaged Haft"},
    {"Addon_Hatchet_BegrimedHead", "Begrimed Head"},
    {"Addon_Hatchet_BerusToxin", "Yellowed Cloth"},
    {"Addon_Hatchet_CoarseStone", "Coarse Stone"},
    {"Addon_Hatchet_DeerskinGloves", "Deerskin Gloves"},
    {"Addon_Hatchet_FineStone", "Weighted Head"},
    {"Addon_Hatchet_FlowerBabushka", "Flower Babushka"},
    {"Addon_Hatchet_GlowingConcoction", "Glowing Concoction"},
    {"Addon_Hatchet_InfantryBelt", "Infantry Belt"},
    {"Addon_Hatchet_IridescentHead", "Iridescent Head"},
    {"Addon_Hatchet_LeatherLoop", "Leather Loop"},
    {"Addon_Hatchet_MannaGrassBraid", "Manna Grass Braid"},
    {"Addon_Hatchet_OakHaft", "Oak Haft"},
    {"Addon_Hatchet_PungentFiale", "Soldier's Puttee"},
    {"Addon_Hatchet_RustyHead", "Rusty Head"},
    {"Addon_Hatchet_ShinyPin", "Shiny Pin"},
    {"Addon_Hatchet_VenomousConcoction", "Venomous Concoction"},
    {"Addon_Hatchet_YewSeedBrew", "Wooden Fox"},
    {"Addon_Hatchet_YewSeedConcoction", "Rose Root"},
    {"Addon_HillbillyChainsaw_IridescentBrick", "Filthy Slippers"},
    {"Addon_K22Power_1", "Cat Figurine"},
    {"Addon_K22Power_10", "Rusted Needle"},
    {"Addon_K22Power_11", "Sewer Sludge"},
    {"Addon_K22Power_12", "Madeleine’s Scarf"},
    {"Addon_K22Power_13", "Stale Biscuit"},
    {"Addon_K22Power_14", "Weighty Rattle"},
    {"Addon_K22Power_15", "Forest Stew"},
    {"Addon_K22Power_16", "Spinning Top"},
    {"Addon_K22Power_17", "Drop of Perfume"},
    {"Addon_K22Power_18", "Victor’s Soldier"},
    {"Addon_K22Power_19", "Silencing Cloth"},
    {"Addon_K22Power_2", "Tiny Fingernail"},
    {"Addon_K22Power_20", "Iridescent Pendant"},
    {"Addon_K22Power_3", "Soured Milk"},
    {"Addon_K22Power_4", "Toy Sword"},
    {"Addon_K22Power_5", "Cat’s Eye"},
    {"Addon_K22Power_6", "Madeleine’s Glove"},
    {"Addon_K22Power_7", "Bloody Black Hood"},
    {"Addon_K22Power_8", "Ceremonial Candelabrum"},
    {"Addon_K22Power_9", "Baby Teeth"},
    {"Addon_K24Power_1", "Damaged Syringe"},
    {"Addon_K24Power_10", "Tyrant Gore"},
    {"Addon_K24Power_11", "Serotonin Injector"},
    {"Addon_K24Power_12", "T-Virus Sample"},
    {"Addon_K24Power_13", "Plant 43 Vines"},
    {"Addon_K24Power_14", "Licker Tongue"},
    {"Addon_K24Power_15", "NE-α Parasite"},
    {"Addon_K24Power_16", "Jill’s Sandwich"},
    {"Addon_K24Power_17", "Broken Recovery Coin"},
    {"Addon_K24Power_18", "Depleted Ink Ribbon"},
    {"Addon_K24Power_19", "Shattered S.T.A.R.S. Badge"},
    {"Addon_K24Power_2", "Brian’s Intestine"},
    {"Addon_K24Power_20", "Iridescent Umbrella Badge"},
    {"Addon_K24Power_3", "Visitor Wristband"},
    {"Addon_K24Power_4", "S.T.A.R.S. Field Combat Manual"},
    {"Addon_K24Power_5", "Marvin’s Blood"},
    {"Addon_K24Power_6", "Adrenaline Injector"},
    {"Addon_K24Power_7", "Mikhail’s Eye"},
    {"Addon_K24Power_8", "Zombie Heart"},
    {"Addon_K24Power_9", "Admin Wristband"},
    {"Addon_K25Power_01", "Bent Nail"},
    {"Addon_K25Power_02", "Lively Crickets"},
    {"Addon_K25Power_03", "Burning Candle"},
    {"Addon_K25Power_04", "Leather Strip"},
    {"Addon_K25Power_05", "Wriggling Maggots"},
    {"Addon_K25Power_06", "Spoiled Meal"},
    {"Addon_K25Power_07", "Skewered Rat"},
    {"Addon_K25Power_08", "Flickering Television"},
    {"Addon_K25Power_09", "Liquified Gore"},
    {"Addon_K25Power_10", "Larry’s Blood"},
    {"Addon_K25Power_11", "Torture Pillar"},
    {"Addon_K25Power_12", "Frank’s Heart"},
    {"Addon_K25Power_13", "Larry’s Remains"},
    {"Addon_K25Power_14", "Slice of Frank"},
    {"Addon_K25Power_15", "Greasy Black Lens"},
    {"Addon_K25Power_16", "Original Pain"},
    {"Addon_K25Power_17", "Impaling Wire"},
    {"Addon_K25Power_18", "Chatterer’s Tooth"},
    {"Addon_K25Power_19", "Engineer’s Fang"},
    {"Addon_K25Power_20", "Iridescent Lament Configuration"},
    {"Addon_K26Power_01", "Oil Paints"},
    {"Addon_K26Power_02", "Vibrant Obituary"},
    {"Addon_K26Power_03", "Thick Tar"},
    {"Addon_K26Power_04", "Choclo Corn"},
    {"Addon_K26Power_05", "Automatic Drawing"},
    {"Addon_K26Power_06", "Festering Carrion"},
    {"Addon_K26Power_07", "Velvet Fabric"},
    {"Addon_K26Power_08", "Still Life Crow"},
    {"Addon_K26Power_09", "Untitled Agony"},
    {"Addon_K26Power_10", "Charcoal Stick"},
    {"Addon_K26Power_11", "Darkest Ink"},
    {"Addon_K26Power_12", "O Grief, O Lover"},
    {"Addon_K26Power_13", "Thorny Nest"},
    {"Addon_K26Power_14", "Silver Bell"},
    {"Addon_K26Power_15", "Matias' Baby Shoes"},
    {"Addon_K26Power_16", "Severed Tongue"},
    {"Addon_K26Power_17", "Garden of Rot"},
    {"Addon_K26Power_18", "Ink Egg"},
    {"Addon_K26Power_19", "Severed Hands"},
    {"Addon_K26Power_20", "Iridescent Feather"},
    {"Addon_K28_01", "Wooden Plank"},
    {"Addon_K28_02", "Caffeine Tablets"},
    {"Addon_K28_03", "Mortar and Pestle"},
    {"Addon_K28_04", "Follower’s Cowl"},
    {"Addon_K28_05", "Burnt Letters"},
    {"Addon_K28_06", "Air Freshener"},
    {"Addon_K28_07", "Haddie’s Calendar"},
    {"Addon_K28_08", "Fallen Shingle"},
    {"Addon_K28_09", "Malthinker’s Skull"},
    {"Addon_K28_10", "Worry Stone"},
    {"Addon_K28_11", "Ottomarian Writing"},
    {"Addon_K28_12", "Broken Doll"},
    {"Addon_K28_13", "War Helmet"},
    {"Addon_K28_14", "Destroyed Pillow"},
    {"Addon_K28_15", "Tilling Blade"},
    {"Addon_K28_16", "Boat Key"},
    {"Addon_K28_17", "Field Recorder"},
    {"Addon_K28_18", "Lavalier Microphone"},
    {"Addon_K28_19", "Sacrificial Knife"},
    {"Addon_K28_20", "Iridescent Wooden Plank"},
    {"Addon_K29_01", "Jewel Beetle"},
    {"Addon_K29_02", "Green Herb"},
    {"Addon_K29_03", "Unicorn Medallion"},
    {"Addon_K29_04", "R.P.D. Shoulder Walkie"},
    {"Addon_K29_05", "Loose Crank"},
    {"Addon_K29_06", "Leather Gloves"},
    {"Addon_K29_07", "Lion Medallion"},
    {"Addon_K29_08", "Chalice (Gold)"},
    {"Addon_K29_09", "Bullhorn"},
    {"Addon_K29_10", "Portable Safe"},
    {"Addon_K29_11", "Red Herb"},
    {"Addon_K29_12", "Maiden Medallion"},
    {"Addon_K29_13", "Video Conference Device"},
    {"Addon_K29_14", "Egg (Gold)"},
    {"Addon_K29_15", "Dark Sunglasses"},
    {"Addon_K29_16", "Helicopter Stick"},
    {"Addon_K29_17", "Uroboros Tendril"},
    {"Addon_K29_18", "Uroboros Virus"},
    {"Addon_K29_19", "Lab Photo"},
    {"Addon_K29_20", "Iridescent Uroboros Vial"},
    {"Addon_K30_01", "Gritty Lump"},
    {"Addon_K30_02", "Map of the Realm"},
    {"Addon_K30_03", "Tattered Tabard"},
    {"Addon_K30_04", "Pillaged Mead"},
    {"Addon_K30_05", "Dried Horsemeat"},
    {"Addon_K30_06", "Battleaxe Head"},
    {"Addon_K30_07", "Treated Blade"},
    {"Addon_K30_08", "Cold Steel Manacles"},
    {"Addon_K30_09", "Call To Arms"},
    {"Addon_K30_10", "Sharpened Mount"},
    {"Addon_K30_11", "Grim Iron Mask"},
    {"Addon_K30_12", "Broken Hilt"},
    {"Addon_K30_13", "Ironworker’s Tongs"},
    {"Addon_K30_14", "Town Watch’s Torch"},
    {"Addon_K30_15", "Blacksmith’s Hammer"},
    {"Addon_K30_16", "Flint and Steel"},
    {"Addon_K30_17", "Healing Poultice"},
    {"Addon_K30_18", "Jailer's Chimes"},
    {"Addon_K30_19", "Knight’s Contract"},
    {"Addon_K30_20", "Iridescent Company Banner"},
    {"Addon_K31_01", "Adi Valente #1"},
    {"Addon_K31_02", "High-Power Floodlight"},
    {"Addon_K31_03", "Geographical Readout"},
    {"Addon_K31_04", "High Current Upgrade"},
    {"Addon_K31_05", "Adaptive Lighting"},
    {"Addon_K31_06", "Stereo Remote Mic"},
    {"Addon_K31_07", "Supercharge"},
    {"Addon_K31_08", "Shotgun Speakers"},
    {"Addon_K31_09", "Low-Power Mode"},
    {"Addon_K31_10", "Powdered Glass"},
    {"Addon_K31_11", "Vital Targeting Processor"},
    {"Addon_K31_12", "Brown Noise Generator"},
    {"Addon_K31_13", "Loose Screw"},
    {"Addon_K31_14", "Infrared Upgrade"},
    {"Addon_K31_15", "Randomized Strobes"},
    {"Addon_K31_16", "Advanced Movement Prediction"},
    {"Addon_K31_17", "Ultrasonic Speaker"},
    {"Addon_K31_18", "Expired Batteries"},
    {"Addon_K31_19", "Prototype Rotor"},
    {"Addon_K31_20", "Iridescent Unpublished Manuscript"},
    {"Addon_K32_01", "Broken Security Key"},
    {"Addon_K32_02", "Heavy Water"},
    {"Addon_K32_03", "Kid’s Ball Glove"},
    {"Addon_K32_04", "Nutritional Slurry"},
    {"Addon_K32_05", "Diagnostic Tool (Construction)"},
    {"Addon_K32_06", "Diagnostic Tool (Repair)"},
    {"Addon_K32_07", "Android Arm"},
    {"Addon_K32_08", "Cremated Remains"},
    {"Addon_K32_09", "Foreign Plant Fibers"},
    {"Addon_K32_10", "Live Wires"},
    {"Addon_K32_11", "Cryo Gel"},
    {"Addon_K32_12", "Denied Requisition Form"},
    {"Addon_K32_13", "Iridescent Crystal Shard"},
    {"Addon_K32_14", "Ultrasonic Sensor"},
    {"Addon_K32_15", "Spent Oxygen Tank"},
    {"Addon_K32_16", "Nanomachine Gel"},
    {"Addon_K32_17", "Hyperawareness Spray"},
    {"Addon_K32_18", "Hologram Generator"},
    {"Addon_K32_19", "Soma Family Photo"},
    {"Addon_K32_20", "Crew Manifest"},
    {"Addon_K33_01", "Lambert’s Star Map"},
    {"Addon_K33_02", "Cereal Rations"},
    {"Addon_K33_03", "Ripley's Watch"},
    {"Addon_K33_04", "Ovomorph"},
    {"Addon_K33_05", "Drinking Bird"},
    {"Addon_K33_06", "Crew Headset"},
    {"Addon_K33_07", "Emergency Helmet"},
    {"Addon_K33_08", "Ash’s Innards"},
    {"Addon_K33_09", "Light Wand"},
    {"Addon_K33_10", "Kane’s Helmet"},
    {"Addon_K33_11", "Multipurpose Hatchet"},
    {"Addon_K33_12", "Parker’s Headband"},
    {"Addon_K33_13", "Molted Skin"},
    {"Addon_K33_14", "Brett’s Cap"},
    {"Addon_K33_15", "Semiotic Keyboard"},
    {"Addon_K33_16", "Harpoon Gun"},
    {"Addon_K33_17", "Cat Carrier"},
    {"Addon_K33_18", "Self-Destruct Bolt"},
    {"Addon_K33_19", "Improvised Cattle Prod"},
    {"Addon_K33_20", "Acidic Blood"},
    {"Addon_K34_01", "Strobing Light"},
    {"Addon_K34_02", "Doll Eyes"},
    {"Addon_K34_03", "Tiny Scalpel"},
    {"Addon_K34_04", "Good Guy Box"},
    {"Addon_K34_05", "Power Drill"},
    {"Addon_K34_06", "Electric Carving Knife"},
    {"Addon_K34_07", "Jump Rope"},
    {"Addon_K34_08", "Hair Spray & Candle"},
    {"Addon_K34_09", "Automatic Screwdriver"},
    {"Addon_K34_10", "Portable TV"},
    {"Addon_K34_11", "Silk Pillow"},
    {"Addon_K34_12", "Iridescent Amulet"},
    {"Addon_K34_13", "Plastic Bag"},
    {"Addon_K34_14", "Pile of Nails"},
    {"Addon_K34_15", "Yardstick"},
    {"Addon_K34_16", "Running Shoes"},
    {"Addon_K34_17", "Rat Poison"},
    {"Addon_K34_18", "Straight Razor"},
    {"Addon_K34_19", "Hard Hat"},
    {"Addon_K34_20", "Mirror Shards"},
    {"Addon_K35_01", "Rabbit's Foot"},
    {"Addon_K35_02", "Footprint Cast"},
    {"Addon_K35_03", "Blurry Photo"},
    {"Addon_K35_04", "Slashed Backpack"},
    {"Addon_K35_05", "Punctured Eyeball"},
    {"Addon_K35_06", "Notebook of Theories"},
    {"Addon_K35_07", "Last Known Recording"},
    {"Addon_K35_08", "Sketch Attempt"},
    {"Addon_K35_09", "Victim’s Map"},
    {"Addon_K35_10", "Vanishing Box"},
    {"Addon_K35_11", "Front-Page Article"},
    {"Addon_K35_12", "Hypnotist’s Watch"},
    {"Addon_K35_13", "B-Movie Poster"},
    {"Addon_K35_14", "Device of Undisclosed Origin"},
    {"Addon_K35_15", "Homemade Mask"},
    {"Addon_K35_16", "Obscure Game Cartridge"},
    {"Addon_K35_17", "Discarded Milk Carton"},
    {"Addon_K35_18", "Serum Vial"},
    {"Addon_K35_19", "Captured by the Dark"},
    {"Addon_K35_20", "Iridescent OSS Report"},
    {"Addon_K36_01", "Tattered Headband"},
    {"Addon_K36_02", "Raven's Feather"},
    {"Addon_K36_03", "Trickster's Glove"},
    {"Addon_K36_04", "Crystal Ball"},
    {"Addon_K36_05", "Lantern of Revealing"},
    {"Addon_K36_06", "Potion of Speed"},
    {"Addon_K36_07", "Ring of Telekinesis"},
    {"Addon_K36_08", "Glass Eye"},
    {"Addon_K36_09", "Ring of Spell Storing"},
    {"Addon_K36_10", "Ornate Horn"},
    {"Addon_K36_11", "Cloak of Elvenkind"},
    {"Addon_K36_12", "Boots of Speed"},
    {"Addon_K36_13", "Staff of Withering"},
    {"Addon_K36_14", "Pearl of Power"},
    {"Addon_K36_15", "Robe of Eyes"},
    {"Addon_K36_16", "Dragontooth Dagger"},
    {"Addon_K36_17", "Cloak of Invisibility"},
    {"Addon_K36_18", "Bag of Holding"},
    {"Addon_K36_19", "Vorpal Sword"},
    {"Addon_K36_20", "Iridescent Book of Vile Darkness"},
    {"Addon_K37_01", "Sylph Feather"},
    {"Addon_K37_02", "Ruby Circlet"},
    {"Addon_K37_03", "Cerberus Talon"},
    {"Addon_K37_04", "Clock Tower Gear"},
    {"Addon_K37_05", "Magical Ticket"},
    {"Addon_K37_06", "Moonstone Necklace"},
    {"Addon_K37_07", "Blood-Filled Goblet"},
    {"Addon_K37_08", "Traveler’s Hat"},
    {"Addon_K37_09", "Winged Boots"},
    {"Addon_K37_10", "White Wolf Medallion"},
    {"Addon_K37_11", "Killer Doll"},
    {"Addon_K37_12", "Sunglasses"},
    {"Addon_K37_13", "Force of Echo"},
    {"Addon_K37_14", "Pocket Watch"},
    {"Addon_K37_15", "Medusa’s Hair"},
    {"Addon_K37_16", "Warg’s Fang"},
    {"Addon_K37_17", "Cube of Zoe"},
    {"Addon_K37_18", "Lapis Lazuli"},
    {"Addon_K37_19", "Alucard’s Shield"},
    {"Addon_K37_20", "Iridescent Ring of Vlad"},
    {"Addon_K38_01", "Young Coconut"},
    {"Addon_K38_02", "Sticky Pitch"},
    {"Addon_K38_03", "Creature's Bone"},
    {"Addon_K38_04", "Trainer's Book"},
    {"Addon_K38_05", "Barley Meal"},
    {"Addon_K38_06", "Belaying Pins"},
    {"Addon_K38_07", "Smoked Snapper"},
    {"Addon_K38_08", "Knotted Rope"},
    {"Addon_K38_09", "Spyglass"},
    {"Addon_K38_10", "Waterskin"},
    {"Addon_K38_11", "Unfinished Map"},
    {"Addon_K38_12", "Training Bell"},
    {"Addon_K38_13", "Spiked Collar"},
    {"Addon_K38_14", "Fatty Meat"},
    {"Addon_K38_15", "Leather Harness"},
    {"Addon_K38_16", "Gunpowder Tin"},
    {"Addon_K38_17", "Marlinspike"},
    {"Addon_K38_18", "Ship Figurehead"},
    {"Addon_K38_19", "Torn Novel"},
    {"Addon_K38_20", "Iridescent Wheel Handle"},
    {"Addon_K39_01", "Kaneki’s Wallet"},
    {"Addon_K39_02", "The Black Goat’s Egg"},
    {"Addon_K39_03", "Anteiku Apron"},
    {"Addon_K39_04", "Fresh Coffee"},
    {"Addon_K39_05", "Broken Chain"},
    {"Addon_K39_06", "Kaneki's Satchel"},
    {"Addon_K39_07", "Hide’s Headphones"},
    {"Addon_K39_08", "Taiyaki"},
    {"Addon_K39_09", "Blood-Stained Handkerchief"},
    {"Addon_K39_10", "Mado’s Glove"},
    {"Addon_K39_11", "Hinami’s Umbrella"},
    {"Addon_K39_12", "Rize's Glasses"},
    {"Addon_K39_13", "Aogiri Tree Robe"},
    {"Addon_K39_14", "Amon’s Necktie"},
    {"Addon_K39_15", "Red Spider Lily"},
    {"Addon_K39_16", "CCG ID Card"},
    {"Addon_K39_17", "Red-Headed Centipede"},
    {"Addon_K39_18", "Torture Apparatus"},
    {"Addon_K39_19", "Yamori’s Mask"},
    {"Addon_K39_20", "Iridescent Eye Patch"},
    {"Addon_K40_01", "Help Wanted Ad"},
    {"Addon_K40_02", "Security Guard’s Badge"},
    {"Addon_K40_03", "Restaurant Menu"},
    {"Addon_K40_04", "Rotten Pizza"},
    {"Addon_K40_05", "Ripped Curtain"},
    {"Addon_K40_06", "Greasy Paper Plate"},
    {"Addon_K40_07", "Streamers"},
    {"Addon_K40_08", "Party Hat"},
    {"Addon_K40_09", "Office Phone"},
    {"Addon_K40_10", "Chica’s Bib"},
    {"Addon_K40_11", "Bonnie’s Guitar Strings"},
    {"Addon_K40_12", "Foxy’s Hook"},
    {"Addon_K40_13", "Purple Guy Drawing"},
    {"Addon_K40_14", "Freddy’s Hat"},
    {"Addon_K40_15", "Loot Bag"},
    {"Addon_K40_16", "Access Panel"},
    {"Addon_K40_17", "Celebrate! Poster"},
    {"Addon_K40_18", "Faz-Coin"},
    {"Addon_K40_19", "Endo CPU"},
    {"Addon_K40_20", "Iridescent Remnant"},
    {"Addon_K41_01", "Sticky Lozenge"},
    {"Addon_K41_02", "Broken Tiara"},
    {"Addon_K41_03", "Luckless Mouse"},
    {"Addon_K41_04", "First Libretto"},
    {"Addon_K41_05", "Wriggling Parasite"},
    {"Addon_K41_06", "Chunk of Malai"},
    {"Addon_K41_07", "Crumpled Sheet Music"},
    {"Addon_K41_08", "Defective Metronome"},
    {"Addon_K41_09", "Pig's Eye"},
    {"Addon_K41_10", "Chicken Head"},
    {"Addon_K41_11", "Janjira's Hand"},
    {"Addon_K41_12", "Dulled Knife"},
    {"Addon_K41_13", "Spattered Handkerchief"},
    {"Addon_K41_14", "Framed Newspaper"},
    {"Addon_K41_15", "Lorenza's Remains"},
    {"Addon_K41_16", "Shredded Gown"},
    {"Addon_K41_17", "Rotten Swine"},
    {"Addon_K41_18", "Theater Binoculars"},
    {"Addon_K41_19", "Queen's Scepter"},
    {"Addon_K41_20", "Mysterious Elixir"},
    {"Addon_K42_01", "Orderly ID"},
    {"Addon_K42_02", "Bead Maze"},
    {"Addon_K42_03", "Shattered Wrist Rocket"},
    {"Addon_K42_04", "Stained Glass Mural"},
    {"Addon_K42_05", "Smashed Cassette Deck"},
    {"Addon_K42_06", "Bloody Roller Skate"},
    {"Addon_K42_07", "Gutted Supercom"},
    {"Addon_K42_08", "Mid-Century Radio"},
    {"Addon_K42_09", "Clock Hands"},
    {"Addon_K42_10", "Electrode Cap"},
    {"Addon_K42_11", "Forged Death Certificate"},
    {"Addon_K42_12", "Rabbit Remains"},
    {"Addon_K42_13", "Neck Tendril"},
    {"Addon_K42_14", "Victor's Razor Blade"},
    {"Addon_K42_15", "Broken Skateboard"},
    {"Addon_K42_16", "Black Widow Spider"},
    {"Addon_K42_17", "Pizza Goggles"},
    {"Addon_K42_18", "Electroshock Collar"},
    {"Addon_K42_19", "Chess Piece"},
    {"Addon_K42_20", "Iridescent Soteria Chip"},
    {"Addon_Kanobo_AkitosCrutch", "Akito's Crutch"},
    {"Addon_Kanobo_BlackenedToenail", "Blackened Toenail"},
    {"Addon_Kanobo_BloodySash", "Bloody Sash"},
    {"Addon_Kanobo_ChildsWoodenSword", "Child's Wooden Sword"},
    {"Addon_Kanobo_ChippedSaihai", "Chipped Saihai"},
    {"Addon_Kanobo_CrackedSakazuki", "Cracked Sakazuki"},
    {"Addon_Kanobo_InkLion", "Ink Lion"},
    {"Addon_Kanobo_KanaianzenTalisman", "Kanai-anzen Talisman"},
    {"Addon_Kanobo_LionFang", "Lion Fang"},
    {"Addon_Kanobo_PaperLantern", "Paper Lantern"},
    {"Addon_Kanobo_PolishedMaedate", "Polished Maedate"},
    {"Addon_Kanobo_RenjirosBloodyGlove", "Renjiro’s Bloody Glove"},
    {"Addon_Kanobo_RottingRope", "Rotting Rope"},
    {"Addon_Kanobo_ScalpedTopknot", "Scalped Topknot"},
    {"Addon_Kanobo_ShatteredWakizashi", "Shattered Wakizashi"},
    {"Addon_Kanobo_SplinteredHull", "Splintered Hull"},
    {"Addon_Kanobo_TearSoakedTenugui", "Tear Soaked Tenugui"},
    {"Addon_Kanobo_WoodenOniMask", "Wooden Oni Mask"},
    {"Addon_Kanobo_YamaokaFamilyCrest", "Iridescent Family Crest"},
    {"Addon_Kanobo_YamaokaSashimono", "Yamaoka Sashimono"},
    {"Addon_Key_001", "Friendship Charm"},
    {"Addon_Key_002", "Prayer Beads"},
    {"Addon_Key_003", "Shrill Whistle"},
    {"Addon_Key_004", "Gold Token"},
    {"Addon_Key_005", "Blood Amber"},
    {"Addon_Key_006", "Milky Glass"},
    {"Addon_Key_007", "Weaved Ring"},
    {"Addon_Key_008", "Braided Bauble"},
    {"Addon_Key_WeddingRing", "Unique Wedding Ring"},
    {"Addon_Killer_Halloween2020", "Blight Serum"},
    {"ADDON_Lastbreath_AtaxicRespiration", "Ataxic Respiration"},
    {"ADDON_Lastbreath_BadManLastBreath", "\"Bad Man's\" Last Breath"},
    {"ADDON_Lastbreath_DullBracelet", "Dull Bracelet"},
    {"ADDON_Lastbreath_HeavyPanting", "Heavy Panting"},
    {"ADDON_Lastbreath_JennerLastBreath", "Jenner's Last Breath"},
    {"ADDON_Lastbreath_KavanaghLastBreath", "Kavanagh's Last Breath"},
    {"ADDON_Lastbreath_Matchbox", "Matchbox"},
    {"ADDON_Lastbreath_SpasmodicBreath", "Spasmodic Breath"},
    {"ADDON_LFChainsaw_AwardWinningChili", "Award-Winning Chili"},
    {"ADDON_LFChainsaw_BeastsMarks", "The Beast's Marks"},
    {"ADDON_LFChainsaw_BegrimedChain", "Begrimed Chains"},
    {"ADDON_LFChainsaw_CarburatorGuide", "Carburetor Tuning Guide"},
    {"ADDON_LFChainsaw_ChainsawFile", "Chainsaw File"},
    {"ADDON_LFChainsaw_Chili", "Chili"},
    {"ADDON_LFChainsaw_DepthGaugeRake", "Depth Gauge Rake"},
    {"ADDON_LFChainsaw_GrislyChains", "Grisly Chain"},
    {"ADDON_LFChainsaw_HomemadeMuffler", "Homemade Muffler"},
    {"ADDON_LFChainsaw_IridescentFlesh", "Iridescent Flesh"},
    {"ADDON_LFChainsaw_KnifeScratches", "Knife Scratches"},
    {"ADDON_LFChainsaw_LightChassis", "Light Chassis"},
    {"ADDON_LFChainsaw_LongGuideBar", "Long Guide Bar"},
    {"ADDON_LFChainsaw_PrimerBulb", "Primer Bulb"},
    {"ADDON_LFChainsaw_RustedChain", "Rusted Chain"},
    {"ADDON_LFChainsaw_ShopLubricant", "Shop Lubricant"},
    {"ADDON_LFChainsaw_SparkPlug", "Spark Plug"},
    {"ADDON_LFChainsaw_SpeedLimiter", "Speed Limiter"},
    {"ADDON_LFChainsaw_TheGrease", "The Grease"},
    {"ADDON_LFChainsaw_VegetableOil", "Vegetable Oil"},
    {"Addon_Map_001", "Glowing Ink"},
    {"Addon_Map_002", "Retardant Jelly"},
    {"Addon_Map_003", "Gnarled Compass"},
    {"Addon_Map_004", "Crimson Stamp"},
    {"Addon_Map_005", "Odd Stamp"},
    {"Addon_Map_006", "Unusual Stamp"},
    {"Addon_Map_007", "Sharpened Flint"},
    {"Addon_Map_008", "Battered Tape"},
    {"Addon_Map_009", "Yellow Wire"},
    {"Addon_Medkit_001", "Bandages"},
    {"Addon_Medkit_002", "Gel Dressings"},
    {"Addon_Medkit_003", "Medical Scissors"},
    {"Addon_Medkit_004", "Butterfly Tape"},
    {"Addon_Medkit_005", "Sponge"},
    {"Addon_Medkit_006", "Rubber Gloves"},
    {"Addon_Medkit_007", "Styptic Agent"},
    {"Addon_Medkit_008", "Anti-Exhaustion Syringe"},
    {"ADDON_medkit_abdominaldressing", "Abdominal Dressing"},
    {"Addon_Medkit_BlightedSyringe", "Refined Serum"},
    {"ADDON_medkit_gauzeroll", "Gauze Roll"},
    {"ADDON_medkit_needleandthread", "Needle & Thread"},
    {"ADDON_medkit_selfadherentwrap", "Self Adherent Wrap"},
    {"ADDON_medkit_surgicalsuture", "Surgical Suture"},
    {"Addon_PhantomTrap_BloodiedMud", "Bloodied Mud"},
    {"Addon_PhantomTrap_BloodiedWater", "Bloodied Water"},
    {"Addon_PhantomTrap_BogWater", "Bog Water"},
    {"Addon_PhantomTrap_CrackedTurtleEgg", "Cracked Turtle Egg"},
    {"Addon_PhantomTrap_CypressNecklet", "Cypress Necklet"},
    {"Addon_PhantomTrap_DeadFlyMud", "Dead Fly Mud"},
    {"Addon_PhantomTrap_DisfiguredEar", "Disfigured Ear"},
    {"Addon_PhantomTrap_DragonflyWings", "Dragonfly Wings"},
    {"Addon_PhantomTrap_DriedCicada", "Dried Cicada"},
    {"Addon_PhantomTrap_GranmasHeart", "Granma's Heart"},
    {"Addon_PhantomTrap_HalfEggshell", "Half Eggshell"},
    {"Addon_PhantomTrap_MintRag", "Mint Rag"},
    {"Addon_PhantomTrap_PowderedEggshell", "Powdered Eggshell"},
    {"Addon_PhantomTrap_PussyWillowCatkins", "Pussy Willow Catkins"},
    {"Addon_PhantomTrap_RopeNecklet", "Rope Necklet"},
    {"Addon_PhantomTrap_RustyShackles", "Rusty Shackles"},
    {"Addon_PhantomTrap_ScarredHand", "Scarred Hand"},
    {"Addon_PhantomTrap_SwampOrchidNecklet", "Swamp Orchid Necklet"},
    {"Addon_PhantomTrap_WaterloggedShoe", "Waterlogged Shoe"},
    {"Addon_PhantomTrap_WillowWreath", "Willow Wreath"},
    {"Addon_PhaseWalker_BloodyHairBrooch", "Mother's Glasses"},
    {"Addon_PhaseWalker_DirtyUwabaki", "Uchiwa"},
    {"Addon_PhaseWalker_DriedCherryBlossom", "Dried Cherry Blossom"},
    {"Addon_PhaseWalker_FathersGlasses", "Kintsugi Teacup"},
    {"Addon_PhaseWalker_GiftedBambooComb", "Gifted Bamboo Comb"},
    {"Addon_PhaseWalker_JuniperBonsai", "Juniper Bonsai"},
    {"Addon_PhaseWalker_KaiunTalisman", "Kaiun Talisman"},
    {"Addon_PhaseWalker_KatanaTsuba", "Katana Tsuba"},
    {"Addon_PhaseWalker_KatsumoriTalisman", "Senko Hanabi"},
    {"Addon_PhaseWalker_MotherDaughterRing", "Mother-Daughter Ring"},
    {"Addon_PhaseWalker_MuddySportsDayCap", "Muddy Sports Day Cap"},
    {"Addon_PhaseWalker_OrigamiCrane", "Origami Crane"},
    {"Addon_PhaseWalker_PrayerBeadsBracelet", "Furin"},
    {"Addon_PhaseWalker_RinsBrokenWatch", "Rin's Broken Watch"},
    {"Addon_PhaseWalker_RustyFlute", "Rusty Flute"},
    {"Addon_PhaseWalker_ShiawaseAmulet", "Shiawase Amulet"},
    {"Addon_PhaseWalker_WakizashiSaya", "Wakizashi Saya"},
    {"Addon_PhaseWalker_WhiteHairRibbon", "White Hair Ribbon"},
    {"Addon_PhaseWalker_YakuyokeAmulet", "Yakuyoke Amulet"},
    {"Addon_PhaseWalker_Zori", "Zōri"},
    {"Addon_Plague_AshenApple", "Ashen Apple"},
    {"Addon_Plague_BlackIncense", "Black Incense"},
    {"Addon_Plague_DevoteesAmulet", "Devotee's Amulet"},
    {"Addon_Plague_EmeticPotion", "Emetic potion"},
    {"Addon_Plague_ExorcismAmulet", "Exorcism Amulet"},
    {"Addon_Plague_HealingSalve", "Healing Salve"},
    {"Addon_Plague_HematiteSeal", "Hematite Seal"},
    {"Addon_Plague_IncensedOintment", "Incensed Ointment"},
    {"Addon_Plague_InfectedEmetic", "Infected Emetic"},
    {"Addon_Plague_IridescentSeal", "Iridescent Seal"},
    {"Addon_Plague_LimestoneSeal", "Limestone Seal"},
    {"Addon_Plague_OlibanumIncense", "Olibanum Incense"},
    {"Addon_Plague_PotentTincture", "Potent Tincture"},
    {"Addon_Plague_PrayerApple", "Blessed Apple"},
    {"Addon_Plague_PrayerTabletFragment", "Prayer Tablet Fragment"},
    {"Addon_Plague_ProphylacticAmulet", "Prophylactic Amulet"},
    {"Addon_Plague_RubbingOil", "Rubbing Oil"},
    {"Addon_Plague_SeveredToe", "Severed Toe"},
    {"Addon_Plague_VileEmetic", "Vile Emetic"},
    {"Addon_Plague_WorshipTablet", "Worship Tablet"},
    {"Addon_ReverseBearTrap_AmandasLetter", "Amanda's Letter"},
    {"Addon_ReverseBearTrap_AmandasSecret", "Amanda's Secret"},
    {"Addon_ReverseBearTrap_BagofGears", "Bag of Gears"},
    {"Addon_ReverseBearTrap_CombatStraps", "Combat Straps"},
    {"Addon_ReverseBearTrap_CrateofGears", "Crate of Gears"},
    {"Addon_ReverseBearTrap_FaceMask", "Face Mask"},
    {"Addon_ReverseBearTrap_InterlockingRazor", "Interlocking Razor"},
    {"Addon_ReverseBearTrap_JigsawsAnnotatedPlan", "Jigsaw's Annotated Plan"},
    {"Addon_ReverseBearTrap_JigsawsSketch", "Jigsaw's Sketch"},
    {"Addon_ReverseBearTrap_JohnMedicalFile", "John's Medical File"},
    {"Addon_ReverseBearTrap_LastWill", "Last Will"},
    {"Addon_ReverseBearTrap_RazorWires", "Razor Wires"},
    {"Addon_ReverseBearTrap_RuleSetN2", "Rule Set No.2"},
    {"Addon_ReverseBearTrap_RustyAttachments", "Rusty Attachments"},
    {"Addon_ReverseBearTrap_ShatteredSyringe", "Shattered Syringe"},
    {"Addon_ReverseBearTrap_SlowReleasingToxin", "Slow-Release Toxin"},
    {"Addon_ReverseBearTrap_TamperedTimer", "Tampered Timer"},
    {"Addon_ReverseBearTrap_UtilityBlades", "Utility Blades"},
    {"Addon_ReverseBearTrap_VideoTape", "Video Tape"},
    {"Addon_ReverseBearTrap_WorkshopGrease", "Workshop Grease"},
    {"Addon_Rush_AdrenalineVial", "Adrenaline Vial"},
    {"Addon_Rush_AlchemistsRing", "Alchemist’s Ring"},
    {"Addon_Rush_BlightedCrow", "Blighted Crow"},
    {"Addon_Rush_BlightedRat", "Blighted Rat"},
    {"Addon_Rush_CankerThorn", "Canker Thorn"},
    {"Addon_Rush_ChippedMonocle", "Chipped Monocle"},
    {"Addon_Rush_CompoundSeven", "Compound Seven"},
    {"Addon_Rush_CompoundThirtyThree", "Compound Thirty-Three"},
    {"Addon_Rush_CompoundTwentyOne", "Compound Twenty-One"},
    {"Addon_Rush_Foxglove", "Foxglove"},
    {"Addon_Rush_IridescentBlightTag", "Iridescent Blight Tag"},
    {"Addon_Rush_PlaceboTablet", "Placebo Tablet"},
    {"Addon_Rush_PlagueBile", "Plague Bile"},
    {"Addon_Rush_PustulaDust", "Pustula Dust"},
    {"Addon_Rush_RoseTonic", "Rose Tonic"},
    {"Addon_Rush_ShreddedNotes", "Shredded Notes"},
    {"Addon_Rush_SoulChemical", "Soul Chemical"},
    {"Addon_Rush_SummoningStone", "Summoning Stone"},
    {"Addon_Rush_UmbraSalts", "Umbra Salts"},
    {"Addon_Rush_VigosJournal", "Vigo's Journal"},
    {"Addon_Spark_CalmClassI", "\"Calm\" - Class I"},
    {"Addon_Spark_CalmClassII", "\"Calm\" - Class II"},
    {"Addon_Spark_CalmMuYisNotes", "\"Calm\" - Carter's Notes"},
    {"Addon_Spark_DisciplineClassII", "\"Discipline\" - Class II"},
    {"Addon_Spark_DisciplineClassIII", "\"Discipline\" - Class III"},
    {"Addon_Spark_DisciplineMuYisNotes", "\"Discipline\" - Carter's Notes"},
    {"Addon_Spark_HighStimulusElectrode", "High Stimulus Electrode"},
    {"Addon_Spark_IridescentGeneral", "Iridescent King"},
    {"Addon_Spark_JadeCharm", "Iridescent Queen"},
    {"Addon_Spark_MoldyElectrode", "Moldy Electrode"},
    {"Addon_Spark_NanmuCatapult", "Maple Knight"},
    {"Addon_Spark_Obedience_MuYisNotes", "Scrapped Tape"},
    {"Addon_Spark_OrderClassI", "\"Order\" - Class I"},
    {"Addon_Spark_OrderClassII", "\"Order\" - Class II"},
    {"Addon_Spark_OrderMuYisNotes", "\"Order\" - Carter's Notes"},
    {"Addon_Spark_PolishedElectrode", "Polished Electrode"},
    {"Addon_Spark_RestraintClassII", "\"Restraint\" - Class II"},
    {"Addon_Spark_RestraintClassIII", "\"Restraint\" - Class III"},
    {"Addon_Spark_RestraintMuYisNotes", "\"Restraint\" - Carter's Notes"},
    {"Addon_Spark_TigerFangCharm", "Interview Tape"},
    {"Addon_Stalker_BlondHair", "Blonde Hair"},
    {"Addon_Stalker_BoyfriendsMemo", "Boyfriend's Memo"},
    {"Addon_Stalker_DeadRabbit", "Dead Rabbit"},
    {"Addon_Stalker_FragrantTuftOfHair", "Fragrant Tuft of Hair"},
    {"Addon_Stalker_GlassFragment", "Glass Fragment"},
    {"Addon_Stalker_HairBow", "Hair Bow"},
    {"Addon_Stalker_HairBrush", "Hair Brush"},
    {"Addon_Stalker_Jewelry", "Jewelry"},
    {"Addon_Stalker_JewelryBox", "Jewelry Box"},
    {"Addon_Stalker_JMyersMemorial", "J.Myers Memorial"},
    {"Addon_Stalker_JudithsJournal", "Judith's Journal"},
    {"Addon_Stalker_JudithsTombstone", "Judith's Tombstone"},
    {"Addon_Stalker_LockOfHair", "Lock of Hair"},
    {"Addon_Stalker_MemorialFlower", "Memorial Flower"},
    {"Addon_Stalker_MirrorShard", "Mirror Shard"},
    {"Addon_Stalker_ReflectiveFragment", "Reflective Fragment"},
    {"Addon_Stalker_ScratchedMirror", "Scratched Mirror"},
    {"Addon_Stalker_TackyEarrings", "Tacky Earrings"},
    {"Addon_Stalker_TombstonePiece", "Tombstone Piece"},
    {"Addon_Stalker_VanityMirror", "Vanity Mirror"},
    {"Addon_TheOnryo_01", "Videotape Copy"},
    {"Addon_TheOnryo_02", "Old Newspaper"},
    {"Addon_TheOnryo_03", "Cabin Sign"},
    {"Addon_TheOnryo_04", "Mother's Mirror"},
    {"Addon_TheOnryo_05", "Reiko's Watch"},
    {"Addon_TheOnryo_06", "Sea-Soaked Cloth"},
    {"Addon_TheOnryo_07", "Clump of Hair"},
    {"Addon_TheOnryo_08", "Well Stone"},
    {"Addon_TheOnryo_09", "Yoichi's Fishing Net"},
    {"Addon_TheOnryo_10", "Rickety Pinwheel"},
    {"Addon_TheOnryo_11", "Well Water"},
    {"Addon_TheOnryo_12", "Ring Drawing"},
    {"Addon_TheOnryo_13", "Bloody Fingernails"},
    {"Addon_TheOnryo_14", "Mother's Comb"},
    {"Addon_TheOnryo_15", "VCR"},
    {"Addon_TheOnryo_16", "Distorted Photo"},
    {"Addon_TheOnryo_17", "Telephone"},
    {"Addon_TheOnryo_18", "Tape Editing Deck"},
    {"Addon_TheOnryo_19", "Remote Control"},
    {"Addon_TheOnryo_20", "Iridescent Videotape"},
    {"Addon_Toolbox_001", "Scraps"},
    {"Addon_Toolbox_002", "Wire Spool"},
    {"Addon_Toolbox_003", "Clean Rag"},
    {"Addon_Toolbox_004", "Grip Wrench"},
    {"Addon_Toolbox_005", "Hacksaw"},
    {"Addon_Toolbox_006", "Protective Gloves"},
    {"Addon_Toolbox_007", "Brand New Part"},
    {"Addon_Toolbox_008", "Instructions"},
    {"ADDON_toolbox_cuttingwire", "Cutting Wire"},
    {"ADDON_toolbox_socketswivels", "Socket Swivels"},
    {"ADDON_toolbox_springclamp", "Spring Clamp"},
    {"ADDON_TormentMode_BlackStrap", "Black Strap "},
    {"ADDON_TormentMode_BurningManPainting", "Burning Man Painting "},
    {"ADDON_TormentMode_CinderellaMusicBox", "Cinderella Music Box "},
    {"ADDON_TormentMode_CopperRing", "Copper Ring "},
    {"ADDON_TormentMode_CrimsonCeremoneyBook", "Crimson Ceremony Book"},
    {"ADDON_TormentMode_DeadButterfly", "Dead Butterfly "},
    {"ADDON_TormentMode_ForgottenVideotape", "Forgotten Videotape "},
    {"ADDON_TormentMode_IridescentSealofMetatron", "Iridescent Seal of Metatron "},
    {"ADDON_TormentMode_LeadRing", "Lead Ring "},
    {"ADDON_TormentMode_LeopardPrintFabric", "Leopard-Print Fabric  "},
    {"ADDON_TormentMode_LostMemoriesBook", "Lost Memories Book "},
    {"ADDON_TormentMode_MannequinFoot", "Mannequin Foot "},
    {"ADDON_TormentMode_MistyDayRemainsofJudgment", "Misty Day, Remains of Judgment "},
    {"ADDON_TormentMode_ObsidianGoblet", "Obsidian Goblet "},
    {"ADDON_TormentMode_RustcoloredEgg", "Rust-colored Egg "},
    {"ADDON_TormentMode_ScarletEgg", "Scarlet Egg "},
    {"ADDON_TormentMode_Spearhead", "Spearhead "},
    {"ADDON_TormentMode_TabletoftheOppressor", "Tablet of the Oppressor "},
    {"ADDON_TormentMode_ValtielSectPhotograph", "Valtiel Sect Photograph "},
    {"ADDON_TormentMode_WaxDoll", "Wax Doll "},
    {"ADDON_trap_BloodyCoil", "Bloody Coil"},
    {"ADDON_trap_DiamondStone", "Iridescent Stone"},
    {"ADDON_trap_OilyCoil", "Oily Coil"},
    {"ADDON_trap_RustedJaw", "Rusted Jaws"},
    {"ADDON_trap_StitchedBag", "Tension Spring"},
    {"ADDON_trap_TrapSetters", "Coffee Grounds"},
    {"Addon_Trickster_01", "Memento Blades"},
    {"Addon_Trickster_02", "Trick Pouch"},
    {"Addon_Trickster_03", "Killing Part Chords"},
    {"Addon_Trickster_04", "Inferno Wires"},
    {"Addon_Trickster_05", "Ji-woon's Autograph"},
    {"Addon_Trickster_06", "On Target Single"},
    {"Addon_Trickster_07", "Lucky Blade"},
    {"Addon_Trickster_08", "Caged Heart Shoes"},
    {"Addon_Trickster_09", "Tequila Moonrock"},
    {"Addon_Trickster_10", "Bloody Boa"},
    {"Addon_Trickster_11", "Fizz-Spin Soda"},
    {"Addon_Trickster_12", "Waiting for You Watch"},
    {"Addon_Trickster_13", "Ripper Brace"},
    {"Addon_Trickster_14", "Melodious Murder"},
    {"Addon_Trickster_15", "Diamond Cufflinks"},
    {"Addon_Trickster_16", "Edge of Revival Album"},
    {"Addon_Trickster_17", "Trick Blades"},
    {"Addon_Trickster_18", "Cut Thru U Single"},
    {"Addon_Trickster_19", "Death Throes Compilation"},
    {"Addon_Trickster_20", "Iridescent Photocard"},
};

static std::unordered_map<std::string, std::string> g_CharacterNames = {
    {"0", "Dwight Fairfield"},
    {"1", "Meg Thomas"},
    {"2", "Claudette Morel"},
    {"3", "Jake Park"},
    {"4", "Nea Karlsson"},
    {"5", "Laurie Strode"},
    {"6", "Ace Visconti"},
    {"7", "William \"Bill\" Overbeck"},
    {"8", "Feng Min"},
    {"9", "David King"},
    {"10", "Kate Denson"},
    {"11", "Quentin Smith"},
    {"12", "Detective Tapp"},
    {"13", "Adam Francis"},
    {"14", "Jeff Johansen"},
    {"15", "Jane Romero"},
    {"16", "Ashley J. Williams"},
    {"17", "Nancy Wheeler"},
    {"18", "Steve Harrington"},
    {"19", "Yui Kimura"},
    {"20", "Zarina Kassir"},
    {"21", "Cheryl Mason"},
    {"22", "Felix Richter"},
    {"23", "Élodie Rakoto"},
    {"24", "Lee Yun-jin"},
    {"25", "Jill Valentine"},
    {"26", "Leon S. Kennedy"},
    {"27", "Mikaela Reid"},
    {"28", "Jonah Vasquez"},
    {"29", "Yoichi Asakawa"},
    {"30", "Haddie Kaur"},
    {"31", "Ada Wong"},
    {"32", "Rebecca Chambers"},
    {"33", "Vittorio Toscano"},
    {"34", "Thalita Lyra"},
    {"35", "Renato Lyra"},
    {"36", "Gabriel Soma"},
    {"37", "Nicolas Cage"},
    {"38", "Ellen Ripley"},
    {"39", "Alan Wake"},
    {"40", "Sable Ward"},
    {"41", "Aestri Yazar"},
    {"42", "Lara Croft"},
    {"43", "Trevor Belmont"},
    {"44", "Taurie Cain"},
    {"45", "Orela Rose"},
    {"46", "Rick Grimes"},
    {"47", "Michonne Grimes"},
    {"48", "Vee Boonyasak"},
    {"49", "Dustin Henderson"},
    {"50", "Eleven"},
    {"51", "Kwon Tae-young"},
    {"268435456", "The Trapper"},
    {"268435457", "The Wraith"},
    {"268435458", "The Hillbilly"},
    {"268435459", "The Nurse"},
    {"268435460", "The Hag"},
    {"268435461", "The Shape"},
    {"268435462", "The Doctor"},
    {"268435463", "The Huntress"},
    {"268435464", "The Cannibal"},
    {"268435465", "The Nightmare"},
    {"268435466", "The Pig"},
    {"268435467", "The Clown"},
    {"268435468", "The Spirit"},
    {"268435469", "The Legion"},
    {"268435470", "The Plague"},
    {"268435471", "The Ghost Face"},
    {"268435472", "The Demogorgon"},
    {"268435473", "The Oni"},
    {"268435474", "The Deathslinger"},
    {"268435475", "The Executioner"},
    {"268435476", "The Blight"},
    {"268435477", "The Twins"},
    {"268435478", "The Trickster"},
    {"268435479", "The Nemesis"},
    {"268435480", "The Cenobite"},
    {"268435481", "The Artist"},
    {"268435482", "The Onryō"},
    {"268435483", "The Dredge"},
    {"268435484", "The Mastermind"},
    {"268435485", "The Knight"},
    {"268435486", "The Skull Merchant"},
    {"268435487", "The Singularity"},
    {"268435488", "The Xenomorph"},
    {"268435489", "The Good Guy"},
    {"268435490", "The Unknown"},
    {"268435491", "The Lich"},
    {"268435492", "The Dark Lord"},
    {"268435493", "The Houndmaster"},
    {"268435494", "The Ghoul"},
    {"268435495", "The Animatronic"},
    {"268435496", "The Krasue"},
    {"268435497", "The First"},
};

static std::unordered_map<std::string, std::string> g_PerkNames = {
    {"Ace_In_The_Hole", "Ace in the Hole"},
    {"Adrenaline", "Adrenaline"},
    {"Aftercare", "Aftercare"},
    {"Agitation", "Agitation"},
    {"Alert", "Alert"},
    {"AnyMeansNecessary", "Any Means Necessary"},
    {"Autodidact", "Autodidact"},
    {"Babysitter", "Babysitter"},
    {"Balanced_Landing", "Balanced Landing"},
    {"Bamboozle", "Bamboozle"},
    {"BBQAndChilli", "Barbecue & Chili"},
    {"BeastOfPrey", "Beast of Prey"},
    {"BetterTogether", "Better Together"},
    {"Bitter_Murmur", "Bitter Murmur"},
    {"BloodEcho", "Blood Echo"},
    {"BloodHound", "Bloodhound"},
    {"BloodPact", "Blood Pact"},
    {"BloodWarden", "Blood Warden"},
    {"BoilOver", "Boil Over"},
    {"Bond", "Bond"},
    {"BoonDestroyer", "Shattered Hope"},
    {"BorrowedTime", "Borrowed Time"},
    {"Botany_Knowledge", "Botany Knowledge"},
    {"Breakdown", "Breakdown"},
    {"Breakout", "Breakout"},
    {"Brutal_Strength", "Brutal Strength"},
    {"BuckleUp", "Buckle Up"},
    {"BuiltToLast", "Built to Last"},
    {"Calm_Spirit", "Calm Spirit"},
    {"Camaraderie", "Camaraderie"},
    {"CorruptIntervention", "Corrupt Intervention"},
    {"Coulrophobia", "Coulrophobia"},
    {"CruelConfinement", "Cruel Limits"},
    {"Dance_with_me", "Dance With Me"},
    {"Dark_Sense", "Dark Sense"},
    {"DarkDevotion", "Dark Devotion"},
    {"DeadHard", "Dead Hard"},
    {"DeadMansSwitch", "Dead Man’s Switch"},
    {"Deathbound", "Deathbound"},
    {"DecisiveStrike", "Decisive Strike"},
    {"Deerstalker", "Deerstalker"},
    {"Deja_Vu", "Deja Vu"},
    {"Deliverance", "Deliverance"},
    {"DesperateMeasures", "Desperate Measures"},
    {"DetectivesHunch", "Detective's Hunch"},
    {"Discordance", "Discordance"},
    {"Distortion", "Distortion"},
    {"Distressing", "Distressing"},
    {"Diversion", "Diversion"},
    {"DragonsGrip", "Dragon’s Grip"},
    {"Dying_Light", "Dying Light"},
    {"Empathy", "Empathy"},
    {"Enduring", "Enduring"},
    {"FireUp", "Fire Up"},
    {"Fixated", "Fixated"},
    {"FlipFlop", "Flip-Flop"},
    {"ForcedPenance", "Forced Penance"},
    {"ForThePeople", "For the People"},
    {"FranklinsLoss", "Franklin's Demise"},
    {"FurtiveChase", "Furtive Chase"},
    {"Gearhead", "Gearhead"},
    {"GeneratorOvercharge", "Overcharge"},
    {"HangmansTrick", "Scourge Hook: Hangman's Trick"},
    {"HeadOn", "Head On"},
    {"Hex_Devour_Hope", "Hex: Devour Hope"},
    {"Hex_HauntedGround", "Hex: Haunted Ground"},
    {"Hex_HuntressLullaby", "Hex: Huntress Lullaby"},
    {"Hex_Ruin", "Hex: Ruin"},
    {"Hex_The_Third_Seal", "Hex: The Third Seal"},
    {"Hex_Thrill_Of_The_Hunt", "Hex: Thrill of the Hunt"},
    {"HexBloodFavor", "Hex: Blood Favor"},
    {"HexRetribution", "Hex: Retribution"},
    {"HexUndying", "Hex: Undying"},
    {"Hope", "Hope"},
    {"ImAllEars", "I'm All Ears"},
    {"InfectiousFright", "Infectious Fright"},
    {"InnerStrength", "Inner Strength"},
    {"Insidious", "Insidious"},
    {"InTheDark", "Knock Out"},
    {"Iron_Grasp", "Iron Grasp"},
    {"Iron_Will", "Iron Will"},
    {"Ironmaiden", "Iron Maiden"},
    {"K22P01", "Hoarder"},
    {"K22P02", "Oppression"},
    {"K22P03", "Coup de Grâce"},
    {"K23P01", "Starstruck"},
    {"K23P02", "Hex: Crowd Control"},
    {"K23P03", "No Way Out"},
    {"K24P01", "Lethal Pursuer"},
    {"K24P02", "Hysteria"},
    {"K24P03", "Eruption"},
    {"K25P01", "Deadlock"},
    {"K25P02", "Hex: Plaything"},
    {"K25P03", "Scourge Hook: Gift of Pain"},
    {"K26P01", "Grim Embrace"},
    {"K26P02", "Scourge Hook: Pain Resonance"},
    {"K26P03", "Hex: Pentimento"},
    {"K27P01", "Scourge Hook: Floods of Rage"},
    {"K27P02", "Call of Brine"},
    {"K27P03", "Merciless Storm"},
    {"K28P01", "Dissolution"},
    {"K28P02", "Darkness Revealed"},
    {"K28P03", "Septic Touch"},
    {"K29P01", "Superior Anatomy"},
    {"K29P02", "Awakened Awareness"},
    {"K29P03", "Terminus"},
    {"K30P01", "Nowhere to Hide"},
    {"K30P02", "Hex: Face the Darkness"},
    {"K30P03", "Hubris"},
    {"K31P01", "Game Afoot"},
    {"K31P02", "THWACK!"},
    {"K31P03", "Leverage"},
    {"K32P01", "Genetic Limits"},
    {"K32P02", "Forced Hesitation"},
    {"K32P03", "Machine Learning"},
    {"K33P01", "Ultimate Weapon"},
    {"K33P02", "Rapid Brutality"},
    {"K33P03", "Alien Instinct"},
    {"K34P01", "Hex: Two Can Play"},
    {"K34P02", "Friends ‘Til the End"},
    {"K34P03", "Batteries Included"},
    {"K35P01", "Unbound"},
    {"K35P02", "Unforeseen"},
    {"K35P03", "Undone"},
    {"K36P01", "Weave Attunement"},
    {"K36P02", "Languid Touch"},
    {"K36P03", "Dark Arrogance"},
    {"K37P01", "Hex: Wretched Fate"},
    {"K37P02", "Human Greed"},
    {"K37P03", "Dominance"},
    {"K38P01", "All-Shaking Thunder"},
    {"K38P02", "Scourge Hook: Jagged Compass"},
    {"K38P03", "No Quarter"},
    {"K39P01", "Hex: Nothing But Misery"},
    {"K39P02", "Forever Entwined"},
    {"K39P03", "None Are Free"},
    {"K40P01", "Help Wanted"},
    {"K40P02", "Phantom Fear"},
    {"K40P03", "Haywire"},
    {"K41P01", "Ravenous"},
    {"K41P02", "Wandering Eye"},
    {"K41P03", "Hex: Overture of Doom"},
    {"K42P01", "Turn Back The Clock"},
    {"K42P02", "Secret Project"},
    {"K42P03", "Hex: Hive Mind"},
    {"Kindred", "Kindred"},
    {"Leader", "Leader"},
    {"LeftBehind", "Left Behind"},
    {"Lightborn", "Lightborn"},
    {"Lightweight", "Lightweight"},
    {"Lithe", "Lithe"},
    {"LuckyBreak", "Lucky Break"},
    {"MadGrit", "Mad Grit"},
    {"MakeYourChoice", "Make your Choice"},
    {"Mindbreaker", "Mindbreaker"},
    {"MonitorAndAbuse", "Monitor & Abuse"},
    {"Monstrous_Shrine", "Scourge Hook: Monstrous Shrine"},
    {"Nemesis", "Nemesis"},
    {"No_One_Escapes_Death", "Hex: No One Escapes Death"},
    {"No_One_Left_Behind", "No One Left Behind"},
    {"NoMither", "No Mither"},
    {"NurseCalling", "A Nurse's Calling"},
    {"ObjectOfObsession", "Object of Obsession"},
    {"OffTheRecord", "Off the Record"},
    {"Open_Handed", "Open-Handed"},
    {"OverwhelmingPresence", "Overwhelming Presence"},
    {"Pharmacy", "Pharmacy"},
    {"Play_With_Your_Food", "Play With Your Food"},
    {"Plunderers_Instinct", "Plunderer's Instinct"},
    {"Poised", "Poised"},
    {"pop_goes_the_weasel", "Pop Goes the Weasel"},
    {"Predator", "Predator"},
    {"Premonition", "Premonition"},
    {"Prove_Thyself", "Prove Thyself"},
    {"QuickQuiet", "Quick & Quiet"},
    {"Rancor", "Rancor"},
    {"RedHerring", "Red Herring"},
    {"RememberMe", "Remember Me"},
    {"RepressedAlliance", "Repressed Alliance "},
    {"Resilience", "Resilience"},
    {"S24P01", "Appraisal"},
    {"S24P02", "Deception"},
    {"S24P03", "Power Struggle"},
    {"S25P01", "Fast Track"},
    {"S25P02", "Smash Hit"},
    {"S25P03", "Self-Preservation"},
    {"S26P01", "Counterforce"},
    {"S26P02", "Resurgence"},
    {"S26P03", "Blast Mine"},
    {"S27P01", "Bite the Bullet"},
    {"S27P02", "Flashbang"},
    {"S27P03", "Rookie Spirit"},
    {"S28P01", "Clairvoyance"},
    {"S28P02", "Boon: Circle of Healing"},
    {"S28P03", "Boon: Shadow Step"},
    {"S29P01", "Overcome"},
    {"S29P02", "Corrective Action"},
    {"S29P03", "Boon: Exponential"},
    {"S30P01", "Parental Guidance"},
    {"S30P02", "Empathic Connection"},
    {"S30P03", "Boon: Dark Theory"},
    {"S31P01", "Inner Focus"},
    {"S31P02", "Residual Manifest"},
    {"S31P03", "Overzealous"},
    {"S32P01", "Wiretap"},
    {"S32P02", "Reactive Healing"},
    {"S32P03", "Low Profile"},
    {"S33P01", "Better Than New"},
    {"S33P02", "Reassurance"},
    {"S33P03", "Hyperfocus"},
    {"S34P01", "Potential Energy"},
    {"S34P02", "Fogwise"},
    {"S34P03", "Quick Gambit"},
    {"S35P01", "Cut Loose"},
    {"S35P02", "Friendly Competition"},
    {"S35P03", "Teamwork: Power of Two"},
    {"S36P01", "Background Player"},
    {"S36P02", "Blood Rush"},
    {"S36P03", "Teamwork: Collective Stealth"},
    {"S37P01", "Troubleshooter"},
    {"S37P02", "Made for This"},
    {"S37P03", "Scavenger"},
    {"S38P01", "Dramaturgy"},
    {"S38P02", "Scene Partner"},
    {"S38P03", "Plot Twist"},
    {"S39P01", "Lucky Star"},
    {"S39P02", "Chemical Trap"},
    {"S39P03", "Light-footed"},
    {"S40P01", "Champion of Light"},
    {"S40P02", "Boon: Illumination"},
    {"S40P03", "Deadline"},
    {"S41P01", "Invocation: Weaving Spiders"},
    {"S41P02", "Strength in Shadows"},
    {"S41P03", "Wicked"},
    {"S42P01", "Mirrored Illusion"},
    {"S42P02", "Bardic Inspiration"},
    {"S42P03", "Still Sight"},
    {"S43P01", "Finesse"},
    {"S43P02", "Hardened"},
    {"S43P03", "Specialist"},
    {"S44P01", "Eyes of Belmont"},
    {"S44P02", "Exultation"},
    {"S44P03", "Moment of Glory"},
    {"S45P01", "Invocation: Treacherous Crows"},
    {"S45P02", "Clean Break"},
    {"S45P03", "Shoulder the Burden"},
    {"S46P01", "Do No Harm"},
    {"S46P02", "Duty of Care"},
    {"S46P03", "Rapid Response"},
    {"S47P01", "Apocalyptic Ingenuity"},
    {"S47P02", "Come and Get Me!"},
    {"S47P03", "Teamwork: Toughen Up"},
    {"S48P01", "Conviction"},
    {"S48P02", "Last Stand"},
    {"S48P03", "Teamwork: Throw Down"},
    {"S49P01", "Road Life"},
    {"S49P02", "ONE-TWO-THREE-FOUR!"},
    {"S49P03", "Ghost Notes"},
    {"S50P01", "Bada Bada Boom"},
    {"S50P02", "Change of Plan"},
    {"S50P03", "Teamwork: Full Circuit"},
    {"S51P01", "Extrasensory Perception"},
    {"S51P02", "We See You"},
    {"S51P03", "Teamwork: Soft-Spoken"},
    {"S52P01", "Flow State"},
    {"S52P02", "A Place For Us"},
    {"S52P03", "Five Moves Ahead"},
    {"Saboteur", "Saboteur"},
    {"Save_The_Best_For_Last", "Save the best for last"},
    {"SecondWind", "Second Wind"},
    {"Self_Care", "Self-Care"},
    {"SelfSufficient", "Unbreakable"},
    {"Shadowborn", "Shadowborn"},
    {"Slippery_Meat", "Slippery Meat"},
    {"Sloppy_Butcher", "Sloppy Butcher"},
    {"Small_Game", "Small Game"},
    {"SoleSurvivor", "Sole Survivor"},
    {"Solidarity", "Solidarity"},
    {"SoulGuard", "Soul Guard"},
    {"Spies_From_The_Shadows", "Spies from the Shadows"},
    {"Spine_Chill", "Spine Chill"},
    {"SpiritFury", "Spirit Fury"},
    {"Sprint_Burst", "Sprint Burst"},
    {"StakeOut", "Stake Out"},
    {"Streetwise", "Streetwise"},
    {"Stridor", "Stridor"},
    {"Surge", "Surge"},
    {"Surveillance", "Surveillance"},
    {"Technician", "Technician"},
    {"Tenacity", "Tenacity"},
    {"TerritorialImperative", "Territorial Imperative"},
    {"Thanatophobia", "Thanatophobia"},
    {"TheMettleOfMan", "Mettle of Man"},
    {"This_Is_Not_Happening", "This Is Not Happening"},
    {"ThrillingTremors", "Thrilling Tremors"},
    {"Tinkerer", "Tinkerer"},
    {"TrailofTorment", "Trail of Torment"},
    {"Unnerving_Presence", "Unnerving Presence"},
    {"Unrelenting", "Unrelenting"},
    {"Up_The_Ante", "Up the Ante"},
    {"Urban_Evasion", "Urban Evasion"},
    {"Vigil", "Vigil"},
    {"Visionary", "Visionary"},
    {"WakeUp", "Wake Up!"},
    {"WellMakeIt", "We'll make it"},
    {"WereGonnaLiveForever", "We're Gonna Live Forever"},
    {"Whispers", "Whispers"},
    {"WindowsOfOpportunity", "Windows of Opportunity"},
    {"ZanshinTactics", "Zanshin Tactics"},
};


static std::unordered_map<std::string, std::string> g_FriendlyNameCache;

static std::string GetFriendlyName(const std::string& internalName, int type) {
    // type: 0 = Perk, 1 = Item/Power, 2 = Addon, 3 = Character
    std::string cacheKey = std::to_string(type) + "_" + internalName;
    if (g_FriendlyNameCache.count(cacheKey)) return g_FriendlyNameCache[cacheKey];

    auto findCaseInsensitive = [](const std::unordered_map<std::string, std::string>& map, const std::string& query) -> std::string {
        std::string q = query;
        std::transform(q.begin(), q.end(), q.begin(), ::tolower);
        for (const auto& pair : map) {
            std::string k = pair.first;
            std::transform(k.begin(), k.end(), k.begin(), ::tolower);
            if (k == q || k == "item_" + q || k == "addon_" + q || k == "itemaddon_" + q || k == "perk_" + q) return pair.second;
            if (q.find("item_") == 0 && k == q.substr(5)) return pair.second;
            if (q.find("addon_") == 0 && k == q.substr(6)) return pair.second;
            if (q.find("itemaddon_") == 0 && k == q.substr(10)) return pair.second;
            if (q.find("perk_") == 0 && k == q.substr(5)) return pair.second;
        }
        return "";
    };

    std::string result = internalName;
    std::string found;
    if (type == 0) found = findCaseInsensitive(g_PerkNames, internalName);
    else if (type == 1) found = findCaseInsensitive(g_ItemNames, internalName);
    else if (type == 2) found = findCaseInsensitive(g_AddonNames, internalName);
    else if (type == 3) {
        if (g_CharacterNames.count(internalName)) found = g_CharacterNames[internalName];
    }

    if (!found.empty()) result = found;

    g_FriendlyNameCache[cacheKey] = result;
    return result;
}
